---
title: "Plotting in R"
author: "Maria Pachiadaki"
date: "11/16/2021"
output:
  rmdformats::downcute:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
    
knit: (function(input_file, encoding) {
  out_dir <- '.';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

---
```{r setup, include=FALSE}
library(knitr)
library(formatR)
library(rmdformats)
library(palmerpenguins)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
# opts_knit$set(width=75, fig.width=12, fig.height=8)
```

# Dataset

We will use the [palmerpenguins](https://allisonhorst.github.io/palmerpenguins/) dataset. Data were collected and made available by Dr. Kristen Gorman and the Palmer Station, Antarctica LTER, a member of the Long Term Ecological Research Network.

```{r check penguins, echo=TRUE}
head(penguins) #check table structure
```

```{r summarize penguins, echo =TRUE}
library(palmerpenguins) # load the penguins dataset
summary(penguins) #summatize data
```





